// src/app/(auth)/(auth-form)/sign-up/page.tsx
"use client";

import { useActionState } from "react";

import { handleEmailPass } from "~/modules/auth/client";
import { displayNameBounds } from "~/modules/user/client";

import { Form } from "~/shared/components/form";
import { Input } from "~/shared/components/input";
import { ContinueBtn } from "../_components/continue-btn";
import { EmailInput } from "../_components/email-input";
import { PasswordInput } from "../_components/password-input";
import { UsernameInput } from "../_components/username-input";

const SUCCESS_PATH = "/sign-up/email-sent";
const MAGIC_LINK_PATH = "/sign-up/success";

export default function SignUpPage() {
  const [res, action, pending] = useActionState(
    (_: unknown, data: FormData) =>
      handleEmailPass(data, SUCCESS_PATH, MAGIC_LINK_PATH),
    null,
  );

  return (
    <Form action={action} className="flex flex-col gap-2">
      <UsernameInput />
      <Input
        label="Your Name"
        type="text"
        name="displayName"
        placeholder="John Doe"
        minLength={displayNameBounds.minLen}
        maxLength={displayNameBounds.maxLen}
      />
      <EmailInput />
      <PasswordInput />

      {res?.error ? <p className="text-red-500 py-3">{res.error}</p> : null}

      <ContinueBtn pending={pending} />
    </Form>
  );
}

// src/routes/auth/(auth-form)/sign-up/+page.svelte
<script lang="ts">
  import AuthForm from "../auth-form.svelte";
  import { validateSignUpFormData } from "./shared";
  import { Btn, Input, HeadMeta, ErrorBanner } from "$lib/components";
  import LogIn from "lucide-svelte/icons/log-in";
  import { getIssue } from "$lib/utils";

  let { form } = $props();
  let issues = $derived(form?.issues);
</script>

<HeadMeta title="Sign Up"/>

<AuthForm
  heading="Sign Up"
  onSubmit={({ formData, cancel }) => {
    const res = validateSignUpFormData(formData);

    if (!res.error) return;

    cancel();
    issues = res.error.issues;
  }}
>
  <Input
    label="Name"
    placeholder="John Doe"
    type="text"
    error={getIssue(issues, "displayName")}
    name="displayName"
  />

  <Input
    label="Username"
    placeholder="johndoe"
    type="text"
    error={getIssue(issues, "username")}
    name="username"
  />

  <Input
    label="Email"
    placeholder="johndoe@gmail.com"
    type="email"
    error={getIssue(issues, "email")}
    name="email"
  />

  <Input
    label="Password"
    placeholder="********"
    type="password"
    error={getIssue(issues, "password")}
    name="password"
  />

  <ErrorBanner error={form?.error} />

  <Btn class="self-end mt-5">
    <LogIn />

    Continue
  </Btn>
</AuthForm>
